---
- name: Deploy nginx as reverse proxy for app instances
  hosts: all
  become: yes
  vars_files:
    - group_vars/all/vars.yml
    - group_vars/all/vault.yml

  tasks:
    - name: Create directory for Nginx config
      file:
        path: /etc/nginx/conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Generate Nginx configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: '0644'

    - name: Deploy Nginx reverse proxy container
      docker_container:
        name: nginx-proxy
        image: nginx:latest
        state: started
        restart_policy: unless-stopped
        networks:
          - name: proxy-net
        ports:
          - "80:80"
        volumes:
          - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
