{{- if .Values.image.pullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecrets.name }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.credentials.registry .Values.image.credentials.username .Values.image.credentials.password .Values.image.credentials.email (printf "%s:%s" .Values.image.credentials.username .Values.image.credentials.password | b64enc) | b64enc }}
{{- end }}